### ISSUE TITLE
BRT/Rapid Express stops not included in maz-stop file

### ISSUE THREAD

**Issue by bhargavasana** [SANDAG/ABM#101]
I believe this is a bug - https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/scripts/resident/2zoneSkim.py#L178. Premium transit also needs to include B/BRT routes. BRT is not just a future mode. We have routes classified as BRT in base year 2022 too.

**Comment by aletzdy** [comment]
fixed with this [commit](https://github.com/SANDAG/ABM/commit/d260ad44b34cca00064efaf74da19877f1c10a08).
