### ISSUE TITLE
Should KNR and TNC to transit be permitted in the visitor model?

### ISSUE THREAD

**Issue by bhargavasana** [SANDAG/ABM#106]
There are too many transit trips in the visitor model. Should KNR and TNC to transit options be unavailable?
[visitor trip mode choice config](https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/visitor/trip_mode_choice.csv#L99)

**Comment by aletzdy** [comment]
drive transit should not be an option in visitor model according to the original ABM2+ configs. fixed with this [commit](https://github.com/SANDAG/ABM/commit/5b596fb3e74a23f854d6989109f7620041c4a4c1)
