### ISSUE TITLE
Inconsistent time periods in skim settings

### ISSUE THREAD

**Issue by aber-sandag** [SANDAG/ABM#107]
The time periods for the airport models are defined differently than the other models in the network_los settings. Resident, visitor, and crossborder use [0, 6, 12, 25, 32, 48], while airport uses [0, 11, 17, 30, 37, 48]
Resident/visitor: https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/common/network_los.yaml#L46
Crossborder: https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/crossborder/network_los.yaml#L35
Airport: https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/common_airport/network_los.yaml#L52

**Comment by aletzdy** [comment]
fixed with this [commit](https://github.com/SANDAG/ABM/commit/4087159b131525a14386e18eec0b93fb7c0cbc73)
