### ISSUE TITLE
Tour mode choice in Airport Model

### ISSUE THREAD

**Issue by bhargavasana** [SANDAG/ABM#110]
Please confirm that there is no tour mode choice in the airport model. Please remove unnecessary files in the airport configs (ex. https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/common_airport/tour_mode_choice.yaml).

**Comment by hannahccarson** [comment]
@bhargavasana there is no tour mode choice in the airport model, however, activitysim's destination choice model requires a tour mode choice. The tour mode choice uec is setup to return 0, but these files need to be in the setup to prevent a crash in the destination choice model.

**Comment by bhargavasana** [comment]
@hannahccarson thank you. @aletzdy could we discuss this more in the training tomorrow?

**Comment by bhargavasana** [comment]
This is good for now but could be simplified in future.
