### ISSUE TITLE
time_mm for ebike and escooter is greater than 0 for work tours only

### ISSUE THREAD

**Issue by anneku** [SANDAG/ABM#117]
time_mm > 0 only for work tours?

https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/resident/trip_mode_choice_annotate_trips.csv#L43

**Comment by aber-sandag** [comment]
Resolved with BayDAG commit: https://github.com/SANDAG/activitysim/commit/777503395d1804f5864f1d52bac8851097985c97
