### ISSUE TITLE
Possible typo in trip mode choice model spec

### ISSUE THREAD

**Issue by jpn--** [SANDAG/ABM#123]
https://github.com/SANDAG/ABM/blob/bab21560011879d086a5cd1280132fe6a0e34e75/src/asim/configs/resident/trip_mode_choice.csv#L249

This line appears to have a typo, the label refers to `KNR_MIX` but the skim references is `KNROUT_PRM`.

h/t to @vivekyadav26 who found this.

**Comment by JoeJimFlood** [comment]
Apologies to @vivekyadav26 for misspelling your name in that commit message...
