### ISSUE TITLE
Taxi/TNC trips not added to crossborder auto table

### ISSUE THREAD

**Issue by aber-sandag** [SANDAG/ABM#124]
It looks like TNC and taxi trips are not added to the crossborder auto table. This likely makes very little difference due to the very small number of these trips (Taxi usually has 10-20 trips, TNC usually has 0 trips, occasionally 1 trip), but should be updated for consistency.

https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/crossborder/write_trip_matrices_annotate_trips_preprocessor.csv#L54

**Comment by aletzdy** [comment]
This is no longer necessary, since we are only reading in the TNC, TAXI trips through the TNC fleet model.
