### ISSUE TITLE
Remove unused settings in CBX airport model

### ISSUE THREAD

**Issue by bhargavasana** [SANDAG/ABM#128]
https://github.com/SANDAG/ABM/blob/d19f2664cc475142eeb1c9e1628d142fc3226312/src/asim/configs/airport.CBX/trip_mode_choice.yaml#L311-L313

**Comment by bhargavasana** [comment]
Please check if there are other settings that can be dropped here.

**Comment by kelvinnguyenn** [comment]
Closed in #245
