### ISSUE TITLE
Does SAN airport config need addition trip mode choice file

### ISSUE THREAD

**Issue by bhargavasana** [SANDAG/ABM#129]
Is this file necessary - https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/airport.SAN/trip_mode_choice_full.csv? There is one in common_airport - https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/common_airport/trip_mode_choice.csv. Please let me know the reason if trip_mode_choice_full.csv is necessary.

**Comment by aletzdy** [comment]
we should not have it. we are [reading trip_mode_choice.csv in the yaml file](https://github.com/SANDAG/ABM/blob/a1ce98d62569f8b4cab98174fe1256ed5c05b554/src/asim/configs/airport.SAN/trip_mode_choice.yaml#L1). I took it out in this [commit](https://github.com/SANDAG/ABM/commit/8fd6a6c0d3eebb9e05406b52c4fb50e0251f2dd6).
