### ISSUE TITLE
TNC_SHARED calibration constants

### ISSUE THREAD

**Issue by aber-sandag** [SANDAG/ABM#154]
Calibration constants are outdated for TNC_SHARED given that the mode is not available in 2022. Some constants maybe should be the same as TNC_SINGLE, uncertain if some are intended to be different between these modes

**Comment by aber-sandag** [comment]
Example: https://github.com/SANDAG/ABM/commit/321d24ab85b04623f97a145c6ed5840a95479010

**Comment by bhargavasana** [comment]
closed by #148
