### ISSUE TITLE
Mode choice models not factoring in ebike ownership

### ISSUE THREAD

**Issue by JoeJimFlood** [SANDAG/ABM#97]
It looks as though ebike ownership is not properly incorporated into the mode choice models. The last line of the tour mode choice preprocessor adds a variable called [ebike_owner](https://github.com/SANDAG/ABM/blob/ABM3_develop/src/asim/configs/resident/tour_mode_choice_annotate_choosers_preprocessor.csv#L260) to the choosers table, but it's set to just always be equal to zero. I did a quick check of some outputs to a run and it looks as though there's no difference in the ebike share based on ebike ownership.

**Comment by aletzdy** [comment]
fixed with two commits [here ](https://github.com/SANDAG/ABM/commit/fb9f6f1cf1d943733ecd1e123d3f8cd301ebe645)and [here](https://github.com/SANDAG/ABM/commit/b1fda312ae85f1e66fd51fc960eaac22225c5df2).

**Comment by aletzdy** [comment]
The line that includes ebike_owner in the choosers' table is in the yaml file. If you check my first commit, we now include it in the choosers' table

**Comment by JoeJimFlood** [comment]
Sorry, I was confused a bit due to me misunderstanding how columns from other tables can be added using the logsum chooser columns. Thanks for clarifying!

**Comment by JoeJimFlood** [comment]
I checked the results of a model run and notices the ebike tour mode share was a bit higher for households owning ebikes than those that don't. Thanks!
